spring:
  datasource:
    url: ${url}
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

mybatis:
  type-aliases-package: ynu.mavena.entity
  mapper-locations: classpath:mapper/*.xml

