# docker-compose.yaml
version: "3"
services:
  mysql:
    container_name: handmysql
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    expose:
      - "3306"
      
  springboot:
    container_name: springboot
    build:
      context: ./java
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
        url : jdbc:mysql://mysql:3306/sakila
        username : root
        password : root
    depends_on: 
      - mysql
    expose:
      - "8080"
